#<font color='#97171e'>AIT - Master in Data Science</font> 📈
# **Module 9**
# DL : Introduction to Tensorflow

## Installing the libraries

In [7]:
# %pip install tensorflow-gpu==2.0.0


## Import the libraries

In [8]:
import tensorflow as tf
import numpy as np

In [9]:
tf.__version__

'2.16.1'

## Tensors

**What's a tensor?**

Tensors are multi-dimensional arrays with a uniform type (called a dtype). You can see all supported dtypes at tf.dtypes.DType.

If you're familiar with NumPy, tensors are (kind of) like np.arrays.

All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.


### Constants

#### Define

constant() is used to create a Tensor from tensor like objects like list.

`tf.constant(
    value, dtype=None, shape=None, name='Const'
)`

If the argument `dtype` is not specified, then the type is inferred from the type of value, but if `dtype` is specified, the resulting tensor values are cast to the requested dtype.

In [10]:
tensor_20 = tf.constant([[23, 4], [32, 51]])
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

If shape is set, the value is reshaped to match. Scalars are expanded to fill the shape.

`tf.constant(0, shape=(2, 3))`

`tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])`



In [11]:
tf.constant(0, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [12]:
tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

The size of a tensor can be retrieved with .shape()

In [13]:
# Obtener el tamaño de un tensor
tensor_20.shape

TensorShape([2, 2])

#### Get the values of a constant

In [14]:
tensor_20.numpy()

array([[23,  4],
       [32, 51]])

We can convert an array of numpy to a TensorFlow tensor directly

In [15]:
numpy_tensor = np.array([[23,  4], [32, 51]])
tensor_from_numpy = tf.constant(numpy_tensor)
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

### Variables
#### Define a variable

In [16]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Query the values of a variable

In [17]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Changing a specific value of a variable

In [18]:
tf2_variable[0, 2].assign(100)
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

## Tensor operations

In [19]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

#### Adding a scalar to a tensor

In [20]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]])>

#### Multiplying a scalar by a tensor

In [21]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]])>

### Using Numpy functions on TensorFlow tensors

#### Get the squares of all the numbers of a tensor from TensorFlow

In [22]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]])

#### Get the square root of all numbers of a tensor from TensorFlow

In [23]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Scalar product between two tensors

In [24]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]])

### Get the tensors of unique elements and their counts.


In [25]:
tensor = tf.constant([1, 2, 3, 4])

In [26]:
tf.unique_with_counts(tensor)

UniqueWithCounts(y=<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>, idx=<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>, count=<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 1, 1, 1])>)

In [27]:
out1, _, out2 = tf.unique_with_counts(tensor)
print(out1.numpy(), out2.numpy())

[1 2 3 4] [1 1 1 1]


### Concatenate two tensors

In [28]:
tensor = tf.constant([[1, 2], [3, 4]])

In [29]:
tensor_20.numpy()

array([[23,  4],
       [32, 51]])

In [30]:
out = tf.concat([tensor, tensor_20], 1)

In [31]:
out.numpy()

array([[ 1,  2, 23,  4],
       [ 3,  4, 32, 51]])

 ### Casting tensors data types

In [32]:
out1 = tf.cast(tensor, tf.float64)
out1.numpy()

array([[1., 2.],
       [3., 4.]])

### One hot encoding

In [33]:
X = tf.constant([[0, 5, 3], [4, 2, 1]])
out = tf.one_hot(X, 6)

In [34]:
out

<tf.Tensor: shape=(2, 3, 6), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0.]],

       [[0., 0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.]]], dtype=float32)>