#<font color='#97171e'>AIT - Master in Data Science</font> 📈
# **Module 9**
# Exercises 01 - Tensorflow I

In [ ]:
from __future__ import print_function
import tensorflow as tf
import numpy as np

NOTE on notation
* _x, _y, _z, ...: NumPy 0-d or 1-d arrays
* _X, _Y, _Z, ...: NumPy 2-d or higer dimensional arrays
* x, y, z, ...: 0-d or 1-d tensors
* X, Y, Z, ...: 2-d or higher dimensional tensors

## Casting

Q2. Let X be a tensor [[1, 2], [3, 4]] of int32. Convert the data type of X to float64.

Q3. Let X be a tensor [[1, 2], [3, 4]] of int32. Convert the data type of X to float32.

Q4. Let X be a tensor [[1, 2], [3, 4]] of float32. Convert the data type of X to int32.

Q5. Let X be a tensor [[1, 2], [3, 4]] of float32. Convert the data type of X to int64.

## Shapes and Shaping

Q6. Let X be a tensor of [[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]. Create a tensor representing the shape of X.

Q8. Let X be a tensor of [[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]. Create a tensor representing the size (=total number of elements) of X.

## Slicing and Joining

Q19. Lex X be a tensor <br/>
[[ 1 2 3]<br/>
 [ 4 5 6].<br/>
and Y be a tensor<br/>
[[ 7 8 9]<br/>
 [10 11 12]].<br/>
Concatenate X and Y so that the new tensor looks like [[1, 2, 3, 7, 8, 9], [4, 5, 6, 10, 11, 12]].

Q27. Let x be a tensor [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get the tensors of unique elements and their counts.

Q31. Let x be a tensor [[0, 5, 3], [4, 2, 1]]. Convert X into one-hot.