#<font color='#97171e'>AIT - Master in Data Science</font> 📈
# **Module 9**
# Tensor Transformations

In [1]:
from __future__ import print_function
import tensorflow as tf
import numpy as np

NOTE on notation
* _x, _y, _z, ...: NumPy 0-d or 1-d arrays
* _X, _Y, _Z, ...: NumPy 2-d or higer dimensional arrays
* x, y, z, ...: 0-d or 1-d tensors
* X, Y, Z, ...: 2-d or higher dimensional tensors

## Casting

Q2. Let X be a tensor [[1, 2], [3, 4]] of int32. Convert the data type of X to float64.

In [2]:
_X = np.array([[1, 2], [3, 4]], dtype=np.int32)
X = tf.constant(_X)
out = tf.cast(X, tf.float64)
print(out.numpy())

[[1. 2.]
 [3. 4.]]


Q3. Let X be a tensor [[1, 2], [3, 4]] of int32. Convert the data type of X to float32.

In [3]:
_X = np.array([[1, 2], [3, 4]], dtype=np.int32)
X = tf.constant(_X)
out = tf.cast(X, tf.float32)
print(out.numpy())

[[1. 2.]
 [3. 4.]]


Q4. Let X be a tensor [[1, 2], [3, 4]] of float32. Convert the data type of X to int32.

In [4]:
_X = np.array([[1, 2], [3, 4]], dtype=np.float32)
X = tf.constant(_X)
out = tf.cast(X, tf.int32)
print(out.numpy())

[[1 2]
 [3 4]]


Q5. Let X be a tensor [[1, 2], [3, 4]] of float32. Convert the data type of X to int64.

In [5]:
_X = np.array([[1, 2], [3, 4]], dtype=np.float32)
X = tf.constant(_X)
out = tf.cast(X, tf.int64)
print(out.numpy())

[[1 2]
 [3 4]]


## Shapes and Shaping

Q6. Let X be a tensor of [[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]. Create a tensor representing the shape of X.

In [6]:
_X = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
X = tf.constant(_X)
out = tf.shape(X)
print(out.numpy())

[3 2 2]


Q8. Let X be a tensor of [[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]. Create a tensor representing the size (=total number of elements) of X.

In [7]:
_X = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
X = tf.constant(_X)
out = tf.size(X)
print(out.numpy())

12


## Slicing and Joining

Q19. Lex X be a tensor <br/>
[[ 1 2 3]<br/>
 [ 4 5 6].<br/>
and Y be a tensor<br/>
[[ 7 8 9]<br/>
 [10 11 12]].<br/>
Concatenate X and Y so that the new tensor looks like [[1, 2, 3, 7, 8, 9], [4, 5, 6, 10, 11, 12]].

In [8]:
_X = np.array([[1, 2, 3], [4, 5, 6]])
_Y = np.array([[7, 8, 9], [10, 11, 12]])
X = tf.constant(_X)
Y = tf.constant(_Y)
out = tf.concat([X, Y], 1)
print(out.numpy())


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Q27. Let x be a tensor [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get the tensors of unique elements and their counts.

In [9]:
x = tf.constant([2, 2, 1, 5, 4, 5, 1, 2, 3])
out1, _, out2 = tf.unique_with_counts(x)
print(out1.numpy(), out2.numpy())

[2 1 5 4 3] [3 2 2 1 1]


Q31. Let X be a tensor [[0, 5, 3], [4, 2, 1]]. Convert X into one-hot.

In [10]:
X = tf.constant([[0, 5, 3], [4, 2, 1]])
out = tf.one_hot(x, 6)
print(out.numpy())

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
